// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdT9Gre9qNc1-ci_6eLCvPCDN0_Pccp8o',
    appId: '1:154759003826:web:dec3b1ed2ddac6555a53ab',
    messagingSenderId: '154759003826',
    projectId: 'ctse-assignment-01',
    authDomain: 'ctse-assignment-01.firebaseapp.com',
    storageBucket: 'ctse-assignment-01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBox3QMQSt6cSOfiWBiHtfPvitogsMW88M',
    appId: '1:154759003826:android:3fec1869f4e3d4b35a53ab',
    messagingSenderId: '154759003826',
    projectId: 'ctse-assignment-01',
    storageBucket: 'ctse-assignment-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDURQ_rQmc5lEQLdYPA3rzLankZIPFSLo0',
    appId: '1:154759003826:ios:6bc06cbeeb66c2d05a53ab',
    messagingSenderId: '154759003826',
    projectId: 'ctse-assignment-01',
    storageBucket: 'ctse-assignment-01.appspot.com',
    iosClientId: '154759003826-01ie4uvu9r9njo1g96ejn320hqh32f1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDURQ_rQmc5lEQLdYPA3rzLankZIPFSLo0',
    appId: '1:154759003826:ios:6bc06cbeeb66c2d05a53ab',
    messagingSenderId: '154759003826',
    projectId: 'ctse-assignment-01',
    storageBucket: 'ctse-assignment-01.appspot.com',
    iosClientId: '154759003826-01ie4uvu9r9njo1g96ejn320hqh32f1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipies',
  );
}
